---
name: Text-RecordParser
version: 1.4.0
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
abstract: Parse record-oriented data in a text file
license: gpl
resources:
  license: ~
requires:
  Class::Accessor: 0
  IO::Scalar: 0
  List::MoreUtils: 0
  List::Util: 0
  Readonly: 0
  version: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
recommends:
  GraphViz: 0
  Readonly::XS: 0
  Text::TabularDisplay: 1.22
provides:
  Text::RecordParser:
    file: lib/Text/RecordParser.pm
    version: 1.4.0
  Text::RecordParser::Object:
    file: lib/Text/RecordParser/Object.pm
    version: 1.4.0
  Text::RecordParser::Tab:
    file: lib/Text/RecordParser/Tab.pm
    version: 1.4.0
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
