--- #YAML:1.0
name: Text-RecordParser
version: v1.1.1
author:
  - Ken Youens-Clark <kclark@cpan.org>
abstract: Parse record-oriented data in a text file
license: gpl
generated_by: Module::Build version 0.2611, without YAML.pm
