---
abstract: 'Parse record-oriented data in a text file'
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
build_requires:
  Pod::Markdown: 0
  Pod::Readme: 0
  Pod::Select: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.4
  Pod::Markdown: 0
  Pod::Readme: 0
  Pod::Select: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-RecordParser
provides:
  Text::RecordParser:
    file: lib/Text/RecordParser.pm
    version: v1.6.3
  Text::RecordParser::Object:
    file: lib/Text/RecordParser/Object.pm
    version: v1.4.0
  Text::RecordParser::Tab:
    file: lib/Text/RecordParser/Tab.pm
    version: v1.4.0
recommends:
  GraphViz: 0
  Readonly::XS: 0
  Text::TabularDisplay: 1.22
requires:
  Class::Accessor: 0
  IO::Scalar: 0
  List::MoreUtils: 0
  List::Util: 0
  Readonly: 0
  Text::Autoformat: 0
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: v1.6.3
